{"cause":{"code":"AVV_ERR_PLUGIN_NOT_VALID","message":"Plugin must be a function or a promise. Received: 'object'","name":"FastifyError","statusCode":500},"code":"FST_ERR_PLUGIN_NOT_VALID","environment":"local","level":"error","message":"fastify-plugin: Plugin must be a function or a promise. Received: 'object'","ms":"+0ms","name":"FastifyError","stack":"FastifyError: fastify-plugin: Plugin must be a function or a promise. Received: 'object'\n    at manageErr (/Users/ethan/Documents/practice/crossed/backend/node_modules/fastify/fastify.js:632:33)\n    at /Users/ethan/Documents/practice/crossed/backend/node_modules/fastify/fastify.js:618:11\n    at Object._encapsulateThreeParam (/Users/ethan/Documents/practice/crossed/backend/node_modules/avvio/boot.js:600:7)\n    at Boot.timeoutCall (/Users/ethan/Documents/practice/crossed/backend/node_modules/avvio/boot.js:494:5)\n    at Boot.callWithCbOrNextTick (/Users/ethan/Documents/practice/crossed/backend/node_modules/avvio/boot.js:476:19)\n    at release (/Users/ethan/Documents/practice/crossed/backend/node_modules/fastq/queue.js:171:16)\n    at Object.resume (/Users/ethan/Documents/practice/crossed/backend/node_modules/fastq/queue.js:103:7)\n    at /Users/ethan/Documents/practice/crossed/backend/node_modules/avvio/boot.js:116:18\n    at /Users/ethan/Documents/practice/crossed/backend/node_modules/avvio/boot.js:437:7\n    at done (/Users/ethan/Documents/practice/crossed/backend/node_modules/avvio/lib/plugin.js:228:5)","statusCode":500,"timestamp":"2024-12-02T00:28:55.583Z"}
{"code":"ECONNREFUSED","environment":"local","level":"error","message":"","ms":"+0ms","stack":"AggregateError [ECONNREFUSED]: \n    at internalConnectMultiple (node:net:1116:18)\n    at afterConnectMultiple (node:net:1683:7)","timestamp":"2024-12-05T01:51:20.632Z"}
